/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegoxo;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class xo extends javax.swing.JFrame {
 
    /**
     * Creates new form xo
     */
    String turno= "X"; 
    JLabel lbs[][]= new JLabel[3][3];
   
    public xo() {
        initComponents();
        lbs[0][0]= cuadro1; 
        lbs[0][1]=cuadro2; 
        lbs[0][2]=cuadro3;
        lbs[1][0]=cuadro4;
        lbs[1][1]=cuadro5;
        lbs[1][2]=cuadro6;
        lbs[2][0]=cuadro7;
        lbs[2][1]=cuadro8;
        lbs[2][2]=cuadro9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cuadro1 = new javax.swing.JLabel();
        cuadro3 = new javax.swing.JLabel();
        cuadro4 = new javax.swing.JLabel();
        cuadro2 = new javax.swing.JLabel();
        cuadro6 = new javax.swing.JLabel();
        cuadro7 = new javax.swing.JLabel();
        cuadro8 = new javax.swing.JLabel();
        cuadro9 = new javax.swing.JLabel();
        cuadro5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        letoca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("xotablero");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        cuadro1.setBackground(new java.awt.Color(255, 255, 255));
        cuadro1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro1.setOpaque(true);
        cuadro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro1MousePressed(evt);
            }
        });

        cuadro3.setBackground(new java.awt.Color(255, 255, 255));
        cuadro3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro3.setOpaque(true);
        cuadro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro3MousePressed(evt);
            }
        });

        cuadro4.setBackground(new java.awt.Color(255, 255, 255));
        cuadro4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro4.setOpaque(true);
        cuadro4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro4MousePressed(evt);
            }
        });

        cuadro2.setBackground(new java.awt.Color(255, 255, 255));
        cuadro2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro2.setOpaque(true);
        cuadro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro2MousePressed(evt);
            }
        });

        cuadro6.setBackground(new java.awt.Color(255, 255, 255));
        cuadro6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro6.setOpaque(true);
        cuadro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro6MousePressed(evt);
            }
        });

        cuadro7.setBackground(new java.awt.Color(255, 255, 255));
        cuadro7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro7.setOpaque(true);
        cuadro7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro7MousePressed(evt);
            }
        });

        cuadro8.setBackground(new java.awt.Color(255, 255, 255));
        cuadro8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro8.setOpaque(true);
        cuadro8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro8MousePressed(evt);
            }
        });

        cuadro9.setBackground(new java.awt.Color(255, 255, 255));
        cuadro9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro9.setOpaque(true);
        cuadro9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro9MousePressed(evt);
            }
        });

        cuadro5.setBackground(new java.awt.Color(255, 255, 255));
        cuadro5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuadro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro5.setOpaque(true);
        cuadro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cuadro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cuadro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(cuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cuadro7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuadro9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadro3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(cuadro6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cuadro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadro3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuadro6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadro7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cuadro9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jugador con X: ");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador con 0: ");
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("JUGAR X-0");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        letoca.setBackground(new java.awt.Color(255, 255, 255));
        letoca.setText("Turno de X");
        letoca.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(letoca)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(letoca)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuadro5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro5MousePressed
        // TODO add your handling code here:
        presionar(1,1);
    }//GEN-LAST:event_cuadro5MousePressed

    private void cuadro9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro9MousePressed
        // TODO add your handling code here:
        presionar(2,2);
    }//GEN-LAST:event_cuadro9MousePressed

    private void cuadro8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro8MousePressed
        // TODO add your handling code here:
        presionar(2,1);
    }//GEN-LAST:event_cuadro8MousePressed

    private void cuadro7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro7MousePressed
        // TODO add your handling code here:
        presionar(2,0);
    }//GEN-LAST:event_cuadro7MousePressed

    private void cuadro6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro6MousePressed
        // TODO add your handling code here:
        presionar(1,2);
    }//GEN-LAST:event_cuadro6MousePressed

    private void cuadro2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro2MousePressed
        // TODO add your handling code here:
        presionar(0,1);
    }//GEN-LAST:event_cuadro2MousePressed

    private void cuadro4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro4MousePressed
        // TODO add your handling code here:
        presionar(1,0);
    }//GEN-LAST:event_cuadro4MousePressed

    private void cuadro3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro3MousePressed
        // TODO add your handling code here:
        presionar(0,2);
    }//GEN-LAST:event_cuadro3MousePressed

    private void cuadro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro1MousePressed
        // TODO add your handling code here:
        presionar(0,0);
    }//GEN-LAST:event_cuadro1MousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
        this.jTextField1.setText(JOptionPane.showInputDialog(null, "Jugador 1:", "Entrada de texto", JOptionPane.QUESTION_MESSAGE));
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        this.jTextField2.setText(JOptionPane.showInputDialog(null, "Jugador 2:", "Entrada de texto", JOptionPane.QUESTION_MESSAGE));
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
        public static String comprobarganador(JLabel[][]lbs){
        
          // Verificar filas horizontal
    for (int i = 0; i < 3; i++) {
        if (lbs[i][0].getText().equals(lbs[i][1].getText()) && 
            lbs[i][1].getText().equals(lbs[i][2].getText()) && 
            !lbs[i][0].getText().equals("")) {
            return lbs[i][0].getText(); 
        }
    }

    // Verificar columnas vertical
    for (int i = 0; i < 3; i++) {
        if (lbs[0][i].getText().equals(lbs[1][i].getText()) && 
            lbs[1][i].getText().equals(lbs[2][i].getText()) && 
            !lbs[0][i].getText().equals("")) {
            return lbs[0][i].getText(); 
        }
    }

    // Verificar diagonal principal
    if (lbs[0][0].getText().equals(lbs[1][1].getText()) && 
        lbs[1][1].getText().equals(lbs[2][2].getText()) && 
        !lbs[0][0].getText().equals("")) {
        return lbs[0][0].getText();
    }
    

    // Verificar diagonal inversa
    if (lbs[0][2].getText().equals(lbs[1][1].getText()) && 
        lbs[1][1].getText().equals(lbs[2][0].getText()) && 
        !lbs[0][2].getText().equals("")) {
       return lbs[0][2].getText(); 
    }

    // Si no hay ganador, devolver null
    return null;
    }
        
    
    
     public void presionar(int fila, int columna) {
        if (lbs[fila][columna].getText().equals("")) {
            lbs[fila][columna].setText(turno);
            cambiarTurno();
            
            String ganador = comprobarganador(lbs);
            if (!ganador.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El ganador es: " + ganador + "!");
                
            }
            
        }
    }
    
    public void cambiarTurno(){
        if(turno.equals("X")){
        turno = "O";
        }
        else{
        turno ="X";
        }
        
        letoca.setText("Turno de "+turno);
}
   
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new xo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuadro1;
    private javax.swing.JLabel cuadro2;
    private javax.swing.JLabel cuadro3;
    private javax.swing.JLabel cuadro4;
    private javax.swing.JLabel cuadro5;
    private javax.swing.JLabel cuadro6;
    private javax.swing.JLabel cuadro7;
    private javax.swing.JLabel cuadro8;
    private javax.swing.JLabel cuadro9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel letoca;
    // End of variables declaration//GEN-END:variables
}
